import { Edit3, PackagePlus, Plus, Search } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { api } from "../lib/api";
import type { Category, Location, Product, Supplier, Uom, Warehouse } from "../lib/types";
import { currency, number } from "../lib/format";
import { Button, DataToolbar, EmptyState, Field, LoadingState, Notice, SearchBox, SectionTitle, Select } from "../components/Ui";
import { Modal } from "../components/Modal";

export function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [uoms, setUoms] = useState<Uom[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Product | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); Promise.all([api.products(search), api.categories(), api.uoms(), api.locations()]).then(([items, categoryList, uomList, locationList]) => { setProducts(items); setCategories(categoryList); setUoms(uomList); setLocations(locationList); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load products")).finally(() => setLoading(false)); };
  useEffect(load, [search]);
  return <div className="page-stack"><SectionTitle eyebrow="CATALOG / PRODUCTS" title="Products" description="Your product master and opening inventory records." action={<Button icon={<Plus size={16} />} onClick={() => { setEditing(null); setOpen(true); }}>New product</Button>} /><section className="panel"><DataToolbar><SearchBox value={search} onChange={setSearch} placeholder="Search product name or SKU..." /><span className="result-count">{products.length} products</span></DataToolbar>{loading ? <LoadingState /> : error ? <div className="panel-pad"><Notice tone="danger">{error}</Notice></div> : products.length === 0 ? <EmptyState icon={<PackagePlus size={22} />} title="No products yet" description="Add the first product to begin tracking stock." action={<Button onClick={() => { setEditing(null); setOpen(true); }} icon={<Plus size={15} />}>Add product</Button>} /> : <div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Unit cost</th><th>Unit</th><th>Status</th><th /></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><div className="product-cell"><span className="product-thumb">{product.name.slice(0, 1)}</span><strong>{product.name}</strong></div></td><td className="mono-cell">{product.sku}</td><td>{product.category?.name || "—"}</td><td>{currency(product.unitCost)}</td><td>{product.uom?.code || "—"}</td><td><span className={`status ${product.isActive ? "status-done" : "status-cancelled"}`}><span />{product.isActive ? "Active" : "Inactive"}</span></td><td><button className="row-action" onClick={() => { setEditing(product); setOpen(true); }}><Edit3 size={14} />Edit</button></td></tr>)}</tbody></table></div>}</section><ProductModal open={open} onClose={() => setOpen(false)} product={editing} categories={categories} uoms={uoms} locations={locations} onSaved={load} /></div>;
}

function ProductModal({ open, onClose, product, categories, uoms, locations, onSaved }: { open: boolean; onClose: () => void; product: Product | null; categories: Category[]; uoms: Uom[]; locations: Location[]; onSaved: () => void }) {
  const [form, setForm] = useState({ sku: "", name: "", unitCost: "", categoryId: "", uomId: "", openingLocationId: "", openingStock: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setForm({ sku: product?.sku || "", name: product?.name || "", unitCost: product ? String(product.unitCost) : "", categoryId: product?.category?.id || categories[0]?.id || "", uomId: product?.uom?.id || uoms[0]?.id || "", openingLocationId: "", openingStock: "" }); setError(""); }, [open, product, categories, uoms]);
  const change = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const body = { sku: form.sku, name: form.name, unitCost: Number(form.unitCost), categoryId: form.categoryId, uomId: form.uomId }; if (product) await api.updateProduct(product.id, body); else await api.createProduct({ ...body, ...(form.openingLocationId && form.openingStock ? { openingStock: { locationId: form.openingLocationId, quantity: Number(form.openingStock) } } : {}) }); onSaved(); onClose(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save product"); } finally { setBusy(false); } }
  return <Modal open={open} onClose={onClose} title={product ? "Edit product" : "New product"} eyebrow="CATALOG / PRODUCT"><form onSubmit={submit}>{error && <Notice tone="danger">{error}</Notice>}<div className="form-grid"><Field label="Product name"><input value={form.name} onChange={(event) => change("name")(event.target.value)} placeholder="e.g. Desk" required /></Field><Field label="SKU"><input value={form.sku} onChange={(event) => change("sku")(event.target.value.toUpperCase())} placeholder="DESK-001" required /></Field><Field label="Per unit cost"><input type="number" step="0.01" min="0" value={form.unitCost} onChange={(event) => change("unitCost")(event.target.value)} placeholder="10.99" required /></Field><Field label="Category"><Select value={form.categoryId} onChange={change("categoryId")}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Unit of measure"><Select value={form.uomId} onChange={change("uomId")}>{uoms.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</Select></Field>{!product && <><Field label="Opening location" hint="Optional, creates an opening ledger record"><Select value={form.openingLocationId} onChange={change("openingLocationId")} placeholder="No opening stock">{locations.map((item) => <option key={item.id} value={item.id}>{item.warehouse?.shortCode} / {item.shortCode}</option>)}</Select></Field>{form.openingLocationId && <Field label="Opening quantity"><input type="number" min="0" step="0.001" value={form.openingStock} onChange={(event) => change("openingStock")(event.target.value)} required /></Field>}</>}</div><div className="modal-foot"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving..." : product ? "Save product" : "Create product"}</Button></div></form></Modal>;
}

type SetupResource = "warehouses" | "locations" | "suppliers";
export function SetupPage({ resource }: { resource: SetupResource }) {
  const [items, setItems] = useState<Array<Warehouse | Location | Supplier>>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); const call = resource === "warehouses" ? api.warehouses() : resource === "locations" ? api.locations() : api.suppliers(); call.then((value) => setItems(value)).catch((err) => setError(err instanceof Error ? err.message : "Unable to load records")).finally(() => setLoading(false)); if (resource === "locations") api.warehouses().then(setWarehouses).catch(() => undefined); };
  useEffect(load, [resource]); const visible = items.filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())); const title = resource[0].toUpperCase() + resource.slice(1);
  return <div className="page-stack"><SectionTitle eyebrow={`SETUP / ${resource.toUpperCase()}`} title={title} description={resource === "warehouses" ? "Warehouse spaces that own inventory locations." : resource === "locations" ? "Named storage locations inside each warehouse." : "Contacts connected to inbound receipts."} action={<Button icon={<Plus size={16} />} onClick={() => setOpen(true)}>New {resource.slice(0, -1)}</Button>} /><section className="panel"><DataToolbar><SearchBox value={search} onChange={setSearch} placeholder={`Search ${resource}...`} /><span className="result-count">{visible.length} records</span></DataToolbar>{loading ? <LoadingState /> : error ? <div className="panel-pad"><Notice tone="danger">{error}</Notice></div> : visible.length === 0 ? <EmptyState icon={<PackagePlus size={22} />} title={`No ${resource} yet`} description="Create a record to connect your warehouse data." action={<Button onClick={() => setOpen(true)} icon={<Plus size={15} />}>Create one</Button>} /> : <div className="table-wrap"><table><thead><tr>{resource === "warehouses" ? <><th>Name</th><th>Short code</th><th>Address</th><th>Locations</th></> : resource === "locations" ? <><th>Name</th><th>Short code</th><th>Warehouse</th></> : <><th>Name</th><th>Email</th><th>Phone</th><th>Address</th></>}</tr></thead><tbody>{visible.map((item) => resource === "warehouses" ? <tr key={item.id}><td><strong>{(item as Warehouse).name}</strong></td><td className="mono-cell">{(item as Warehouse).shortCode}</td><td>{(item as Warehouse).address || "—"}</td><td>{(item as Warehouse).locations?.length || 0}</td></tr> : resource === "locations" ? <tr key={item.id}><td><strong>{(item as Location).name}</strong></td><td className="mono-cell">{(item as Location).shortCode}</td><td>{(item as Location).warehouse?.name || warehouses.find((warehouse) => warehouse.id === (item as Location).warehouseId)?.name || "—"}</td></tr> : <tr key={item.id}><td><strong>{(item as Supplier).name}</strong></td><td>{(item as Supplier).email || "—"}</td><td>{(item as Supplier).phone || "—"}</td><td>{(item as Supplier).address || "—"}</td></tr>)}</tbody></table></div>}</section><SetupModal resource={resource} open={open} onClose={() => setOpen(false)} warehouses={warehouses} onSaved={load} /></div>;
}

function SetupModal({ resource, open, onClose, warehouses, onSaved }: { resource: SetupResource; open: boolean; onClose: () => void; warehouses: Warehouse[]; onSaved: () => void }) {
  const [form, setForm] = useState({ name: "", shortCode: "", address: "", warehouseId: "", email: "", phone: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const change = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const body = resource === "warehouses" ? { name: form.name, shortCode: form.shortCode, address: form.address || undefined } : resource === "locations" ? { name: form.name, shortCode: form.shortCode, warehouseId: form.warehouseId } : { name: form.name, email: form.email || undefined, phone: form.phone || undefined, address: form.address || undefined }; await api.createResource(resource, body); onSaved(); onClose(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create record"); } finally { setBusy(false); } }
  return <Modal open={open} onClose={onClose} title={`New ${resource.slice(0, -1)}`} eyebrow={`SETUP / ${resource.toUpperCase()}`}><form onSubmit={submit}>{error && <Notice tone="danger">{error}</Notice>}<div className="form-grid">{resource !== "suppliers" && <Field label="Name"><input value={form.name} onChange={(event) => change("name")(event.target.value)} required /></Field>}{resource === "suppliers" && <Field label="Supplier name"><input value={form.name} onChange={(event) => change("name")(event.target.value)} required /></Field>}{resource !== "suppliers" && <Field label="Short code"><input value={form.shortCode} onChange={(event) => change("shortCode")(event.target.value.toUpperCase())} required /></Field>}{resource === "warehouses" && <Field label="Address"><input value={form.address} onChange={(event) => change("address")(event.target.value)} /></Field>}{resource === "locations" && <Field label="Warehouse"><Select value={form.warehouseId} onChange={change("warehouseId")}>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name} · {warehouse.shortCode}</option>)}</Select></Field>}{resource === "suppliers" && <><Field label="Email"><input type="email" value={form.email} onChange={(event) => change("email")(event.target.value)} /></Field><Field label="Phone"><input value={form.phone} onChange={(event) => change("phone")(event.target.value)} /></Field><Field label="Address"><input value={form.address} onChange={(event) => change("address")(event.target.value)} /></Field></>}</div><div className="modal-foot"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Creating..." : "Create record"}</Button></div></form></Modal>;
}
