import { ClipboardCheck, Download, PackagePlus, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import type { InventoryBalance, Location } from "../lib/types";
import { currency, number } from "../lib/format";
import { Button, DataToolbar, EmptyState, Field, LoadingState, Notice, SearchBox, SectionTitle, Select } from "../components/Ui";
import { Modal } from "../components/Modal";

export function StockPage() {
  const [rows, setRows] = useState<InventoryBalance[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [error, setError] = useState("");
  const load = () => { setLoading(true); Promise.all([api.inventory(search ? { search } : {}), api.locations()]).then(([inventory, locationList]) => { setRows(inventory); setLocations(locationList); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load stock")).finally(() => setLoading(false)); };
  useEffect(load, [search]);
  const filtered = useMemo(() => rows, [rows]);
  return <div className="page-stack"><SectionTitle eyebrow="PRODUCTS / STOCK" title="Stock" description="Current quantities by product and storage location." action={<><Button variant="outline" icon={<Download size={15} />} onClick={() => window.print()}>Export view</Button><Button icon={<ClipboardCheck size={15} />} onClick={() => setModal(true)}>Adjust stock</Button></>} /><section className="panel"><DataToolbar><SearchBox value={search} onChange={setSearch} placeholder="Search products or SKU..." /><span className="result-count">{filtered.length} balances</span></DataToolbar>{loading ? <LoadingState /> : error ? <div className="panel-pad"><Notice tone="danger">{error}</Notice></div> : filtered.length === 0 ? <EmptyState icon={<PackagePlus size={22} />} title="No stock balances" description="Create a product with opening inventory or validate a receipt." /> : <div className="table-wrap"><table><thead><tr><th>Product</th><th>Per unit cost</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Free to use</th><th /></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><div className="product-cell"><span className="product-thumb">{row.product.name.slice(0, 1)}</span><span><strong>{row.product.name}</strong><small className="cell-sub">{row.product.sku}</small></span></div></td><td>{currency(row.product.unitCost)}</td><td><span className="location-label">{row.location.warehouse?.shortCode || "WH"} / {row.location.shortCode}</span><small className="cell-sub">{row.location.name}</small></td><td>{number(row.onHand)}</td><td className="muted-cell">{number(row.reserved)}</td><td><strong className={Number(row.freeToUse) < 0 ? "negative" : "positive"}>{number(row.freeToUse)}</strong></td><td><button className="row-action" onClick={() => setModal(true)}><SlidersHorizontal size={14} />Adjust</button></td></tr>)}</tbody></table></div>}</section><AdjustmentModal open={modal} onClose={() => setModal(false)} rows={rows} locations={locations} onSaved={load} /></div>;
}

function AdjustmentModal({ open, onClose, rows, locations, onSaved }: { open: boolean; onClose: () => void; rows: InventoryBalance[]; locations: Location[]; onSaved: () => void }) {
  const [locationId, setLocationId] = useState(""); const [productId, setProductId] = useState(""); const [counted, setCounted] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const choices = rows.filter((row) => !locationId || row.location.id === locationId); const selected = rows.find((row) => row.product.id === productId && row.location.id === locationId);
  useEffect(() => { if (open) { setLocationId(rows[0]?.location.id || ""); setProductId(rows[0]?.product.id || ""); setCounted(rows[0] ? String(rows[0].onHand) : ""); setReason(""); setError(""); } }, [open, rows]);
  useEffect(() => { if (selected) setCounted(String(selected.onHand)); }, [locationId, productId]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const reference = `WH/ADJ/${Date.now().toString().slice(-6)}`; const adjustment = await api.createDocument("adjustments", { reference, locationId, reason: reason || "Stock count correction", type: "COUNT" }) as { id: string }; await api.addItem("adjustments", adjustment.id, { productId, countedQuantity: Number(counted) }); await api.transition("adjustments", adjustment.id, "ready"); await api.transition("adjustments", adjustment.id, "validate"); onSaved(); onClose(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to validate adjustment"); } finally { setBusy(false); } }
  return <Modal open={open} onClose={onClose} title="Adjust inventory" eyebrow="STOCK / CONTROL"><form onSubmit={submit}><p className="modal-copy">Record a physical count. The difference is written to the stock ledger and audit trail.</p>{error && <Notice tone="danger">{error}</Notice>}<div className="form-grid"><Field label="Location"><Select value={locationId} onChange={setLocationId}>{locations.map((location) => <option value={location.id} key={location.id}>{location.warehouse?.shortCode} / {location.shortCode} · {location.name}</option>)}</Select></Field><Field label="Product"><Select value={productId} onChange={setProductId}>{choices.map((row) => <option value={row.product.id} key={row.product.id}>{row.product.name} · {row.product.sku}</option>)}</Select></Field><Field label="Counted quantity"><input type="number" min="0" step="0.001" value={counted} onChange={(event) => setCounted(event.target.value)} required /></Field><Field label="Reason"><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Cycle count, damage, recount..." /></Field></div><div className="modal-foot"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy || !productId || !locationId}>{busy ? "Validating..." : "Validate adjustment"}</Button></div></form></Modal>;
}
