import { Activity, BellRing, Check, ClipboardList, FileClock, Plus, RefreshCw, ShieldCheck, SlidersHorizontal, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { api } from "../lib/api";
import type { AuditLog, Location, Product, ReorderRule } from "../lib/types";
import { date, number, title } from "../lib/format";
import { Button, DataToolbar, EmptyState, Field, LoadingState, Notice, SearchBox, SectionTitle, Select, StatusPill } from "../components/Ui";
import { Modal } from "../components/Modal";

export function MoveHistoryPage() {
  const [ledger, setLedger] = useState<any[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.ledger(search ? { search } : {}).then(setLedger).catch(() => setLedger([])).finally(() => setLoading(false)); };
  useEffect(load, [search]);
  return <div className="page-stack"><SectionTitle eyebrow="INVENTORY / MOVEMENT" title="Move history" description="An append-only view of every validated stock movement." action={<Button variant="outline" icon={<RefreshCw size={15} />} onClick={load}>Refresh</Button>} /><section className="panel"><DataToolbar><SearchBox value={search} onChange={setSearch} placeholder="Search reference or movement type..." /><span className="result-count">{ledger.length} movements</span></DataToolbar>{loading ? <LoadingState /> : ledger.length === 0 ? <EmptyState icon={<FileClock size={22} />} title="No movements found" description="Validated receipts, deliveries, transfers, and adjustments appear here." /> : <div className="table-wrap"><table><thead><tr><th>Reference</th><th>Product</th><th>From / location</th><th>Quantity</th><th>Balance after</th><th>Actor</th><th>Created</th></tr></thead><tbody>{ledger.map((entry) => <tr key={entry.id}><td><strong className="mono-cell">{title(entry.referenceType)}</strong><small className="cell-sub">{entry.referenceId.slice(0, 8)}...</small></td><td><strong>{entry.product.name}</strong><small className="cell-sub">{entry.product.sku}</small></td><td>{entry.location.warehouse?.shortCode || "WH"} / {entry.location.shortCode}</td><td className={Number(entry.quantityDelta) < 0 ? "negative" : "positive"}>{Number(entry.quantityDelta) > 0 ? "+" : ""}{number(entry.quantityDelta)}</td><td>{number(entry.balanceAfter)}</td><td>{entry.actor?.name || "System"}</td><td>{date(entry.createdAt)}</td></tr>)}</tbody></table></div>}</section></div>;
}

export function ReorderRulesPage() {
  const [rules, setRules] = useState<ReorderRule[]>([]); const [products, setProducts] = useState<Product[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const load = () => Promise.all([api.reorderRules(), api.products(), api.locations()]).then(([ruleList, productList, locationList]) => { setRules(ruleList); setProducts(productList); setLocations(locationList); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load rules"));
  useEffect(() => { void load(); }, []);
  async function remove(id: string) { if (!window.confirm("Delete this reorder rule?")) return; await api.deleteReorderRule(id); void load(); }
  return <div className="page-stack"><SectionTitle eyebrow="SYSTEM / PLANNING" title="Reorder rules" description="Thresholds that surface low stock on the dashboard." action={<Button icon={<Plus size={16} />} onClick={() => setOpen(true)}>New rule</Button>} /><section className="panel">{error && <div className="panel-pad"><Notice tone="danger">{error}</Notice></div>}{rules.length === 0 ? <EmptyState icon={<SlidersHorizontal size={22} />} title="No reorder rules" description="Add a threshold for a product and location." action={<Button onClick={() => setOpen(true)} icon={<Plus size={15} />}>Create rule</Button>} /> : <div className="table-wrap"><table><thead><tr><th>Product</th><th>Location</th><th>Minimum</th><th>Maximum</th><th /></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td><strong>{rule.product.name}</strong><small className="cell-sub">{rule.product.sku}</small></td><td>{rule.location.name}</td><td>{number(rule.minQty)}</td><td>{number(rule.maxQty)}</td><td><button className="row-action danger-action" onClick={() => void remove(rule.id)}><Trash2 size={14} />Delete</button></td></tr>)}</tbody></table></div>}</section><RuleModal open={open} onClose={() => setOpen(false)} products={products} locations={locations} onSaved={() => { setOpen(false); void load(); }} /></div>;
}

function RuleModal({ open, onClose, products, locations, onSaved }: { open: boolean; onClose: () => void; products: Product[]; locations: Location[]; onSaved: () => void }) { const [form, setForm] = useState({ productId: "", locationId: "", minQty: "", maxQty: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const change = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value })); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api.createReorderRule({ productId: form.productId, locationId: form.locationId, minQty: Number(form.minQty), maxQty: form.maxQty ? Number(form.maxQty) : undefined }); onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save rule"); } finally { setBusy(false); } } return <Modal open={open} onClose={onClose} title="New reorder rule" eyebrow="SYSTEM / THRESHOLD"><form onSubmit={submit}>{error && <Notice tone="danger">{error}</Notice>}<div className="form-grid"><Field label="Product"><Select value={form.productId} onChange={change("productId")}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select></Field><Field label="Location"><Select value={form.locationId} onChange={change("locationId")}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</Select></Field><Field label="Minimum quantity"><input type="number" min="0" step="0.001" value={form.minQty} onChange={(event) => change("minQty")(event.target.value)} required /></Field><Field label="Maximum quantity"><input type="number" min="0" step="0.001" value={form.maxQty} onChange={(event) => change("maxQty")(event.target.value)} /></Field></div><div className="modal-foot"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving..." : "Save rule"}</Button></div></form></Modal>; }

export function AuditLogsPage() { const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { api.auditLogs().then(setLogs).catch(() => setLogs([])).finally(() => setLoading(false)); }, []); return <div className="page-stack"><SectionTitle eyebrow="SYSTEM / TRACEABILITY" title="Audit log" description="Who changed what, and when." action={<Button variant="outline" icon={<RefreshCw size={15} />} onClick={() => window.location.reload()}>Refresh</Button>} /><section className="panel">{loading ? <LoadingState /> : logs.length === 0 ? <EmptyState icon={<ShieldCheck size={22} />} title="No audit events" description="Validated stock operations will be recorded here." /> : <div className="table-wrap"><table><thead><tr><th>Action</th><th>Entity</th><th>Entity ID</th><th>Actor</th><th>Created</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id}><td><strong>{title(log.action)}</strong></td><td>{log.entityType}</td><td className="mono-cell">{log.entityId.slice(0, 12)}...</td><td>{log.actor?.name || "System"}</td><td>{date(log.createdAt)}</td></tr>)}</tbody></table></div>}</section></div>; }

export function SettingsPage() { const [notifications, setNotifications] = useState<any[]>([]); useEffect(() => { api.notifications().then(setNotifications).catch(() => undefined); }, []); return <div className="page-stack"><SectionTitle eyebrow="SYSTEM / SETTINGS" title="Settings" description="Workspace access, alerts, and environment status." /><div className="settings-grid"><section className="panel settings-panel"><div className="panel-head"><div><span className="eyebrow">WORKSPACE</span><h2>StockSense API</h2></div><span className="connection-status"><i /> Connected</span></div><div className="settings-row"><span><Activity size={17} /><span><strong>API endpoint</strong><small>Connected application service</small></span></span><code>{import.meta.env.VITE_API_URL || "http://localhost:4000/api/v1"}</code></div><div className="settings-row"><span><ShieldCheck size={17} /><span><strong>Authentication</strong><small>JWT access and refresh tokens</small></span></span><StatusPill status="READY" /></div><div className="settings-row"><span><ClipboardList size={17} /><span><strong>Auditability</strong><small>Ledger and audit records enabled</small></span></span><StatusPill status="DONE" /></div></section><section className="panel settings-panel"><div className="panel-head"><div><span className="eyebrow">ALERT CENTER</span><h2>Notifications</h2></div><BellRing size={18} /></div>{notifications.length === 0 ? <p className="muted-copy">No notifications have been generated.</p> : notifications.slice(0, 5).map((item) => <div className="settings-notification" key={item.id}><span className={`notification-dot ${item.severity.toLowerCase()}`} /><span><strong>{item.title}</strong><small>{item.message}</small></span><Check size={15} /></div>)}</section></div></div>; }
