export const openapi = {
  openapi: "3.0.3",
  info: { title: "StockSense API", version: "1.0.0", description: "Inventory management API for StockSense." },
  servers: [{ url: "http://localhost:4000" }],
  tags: [
    { name: "Auth" }, { name: "Catalog" }, { name: "Inventory" }, { name: "Operations" },
  ],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      Success: { type: "object", properties: { success: { type: "boolean", example: true }, data: {} } },
      Error: { type: "object", required: ["success", "error"], properties: { success: { type: "boolean", example: false }, error: { type: "object", required: ["code", "message", "details"], properties: { code: { type: "string" }, message: { type: "string" }, details: { type: "object" } } } } },
      Id: { type: "string", format: "uuid" },
      DocumentStatus: { type: "string", enum: ["DRAFT", "READY", "WAITING", "DONE", "CANCELLED"] },
    },
    responses: { BadRequest: { description: "Invalid request", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, Unauthorized: { description: "Authentication required" }, Conflict: { description: "Business rule conflict" } },
  },
  paths: {
    "/health": { get: { tags: ["Auth"], responses: { "200": { description: "Health check" } } } },
    "/api/v1/auth/register": { post: { tags: ["Auth"], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "email", "password"], properties: { name: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } } } } }, responses: { "201": { description: "Registered" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/auth/login": { post: { tags: ["Auth"], responses: { "200": { description: "Logged in" }, "401": { $ref: "#/components/responses/Unauthorized" } } } },
    "/api/v1/auth/refresh": { post: { tags: ["Auth"], responses: { "200": { description: "Token refreshed" } } } },
    "/api/v1/auth/logout": { post: { tags: ["Auth"], responses: { "200": { description: "Logged out" } } } },
    "/api/v1/auth/me": { get: { tags: ["Auth"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Current user" }, "401": { $ref: "#/components/responses/Unauthorized" } } } },
    "/api/v1/auth/password/forgot": { post: { tags: ["Auth"], responses: { "200": { description: "OTP requested" } } } },
    "/api/v1/auth/password/verify-otp": { post: { tags: ["Auth"], responses: { "200": { description: "OTP verified" } } } },
    "/api/v1/auth/password/reset": { post: { tags: ["Auth"], responses: { "200": { description: "Password reset" } } } },
    "/api/v1/products": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Products" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Product created" } } } },
    "/api/v1/categories": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Categories" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Category created" } } } },
    "/api/v1/uoms": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "UOMs" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "UOM created" } } } },
    "/api/v1/warehouses": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Warehouses" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Warehouse created" } } } },
    "/api/v1/locations": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Locations" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Location created" } } } },
    "/api/v1/suppliers": { get: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Suppliers" } } }, post: { tags: ["Catalog"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Supplier created" } } } },
    "/api/v1/inventory": { get: { tags: ["Inventory"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Current balances" } } } },
    "/api/v1/stock-ledger": { get: { tags: ["Inventory"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Append-only movement ledger" } } } },
    "/api/v1/dashboard": { get: { tags: ["Inventory"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Operational dashboard" } } } },
    "/api/v1/receipts": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Receipt list" } } }, post: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Receipt created" } } } },
    "/api/v1/receipts/{id}/validate": { post: { tags: ["Operations"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/Id" } }], responses: { "200": { description: "Receipt validated" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/deliveries": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Delivery list" } } }, post: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Delivery created" } } } },
    "/api/v1/deliveries/{id}/validate": { post: { tags: ["Operations"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/Id" } }], responses: { "200": { description: "Delivery validated" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/transfers": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Transfer list" } } }, post: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Transfer created" } } } },
    "/api/v1/transfers/{id}/validate": { post: { tags: ["Operations"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/Id" } }], responses: { "200": { description: "Transfer validated" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/adjustments": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Adjustment list" } } }, post: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Adjustment created" } } } },
    "/api/v1/adjustments/{id}/validate": { post: { tags: ["Operations"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { $ref: "#/components/schemas/Id" } }], responses: { "200": { description: "Adjustment validated" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/reorder-rules": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Reorder rules" } } }, post: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "201": { description: "Reorder rule created" } } } },
    "/api/v1/notifications": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Notifications" } } } },
    "/api/v1/audit-logs": { get: { tags: ["Operations"], security: [{ bearerAuth: [] }], responses: { "200": { description: "Audit logs" } } } },
  },
} as const;
